FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --allow-insecure-repositories && apt-get install -y --allow-unauthenticated kali-archive-keyring && apt-get update && apt-get install -y --no-install-recommends python3 python3-pip python3-dev curl wget git ca-certificates kali-linux-headless seclists && apt-get clean && rm -rf /var/lib/apt/lists/*
